print ("Ampliando mi Proyecto")
print ("Ampliando mi Proyecto 2")
print ("Ampliando mi Proyecto 3")
print ("Ampliando mi Proyecto 4")
print ("Ampliando mi Proyecto 5")
print ("Ampliando mi Proyecto 6")